### PR TITLE
Update weekly runner to update vaccine related blobs for covid portal

### PR DESCRIPTION
**Pull request by senthil10**
Intended to run every Friday and update relevant blobs

### CODE REVIEW

**Review by talavis — CHANGES_REQUESTED** [review]
The updated runner gives me the following error:
```
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
ls: cannot access '/code/vaccine_plots': No such file or directory
```

**Comment by talavis** [comment]
Also: please put the generated files in the output folder.

Everything should be generated and put in that folder and then we have the upload loop at the end. Do not put files in other places.

**Comment by senthil10** [comment]
I will fix them 👍 though its strange it couldn't find the "vaccine_plots" directory, I tried the same script locally and it worked

**Comment by talavis** [comment]
Quick guess: it failed to run the code and thus no folder was created. No matter what: make sure it ends up in output instead.

**Comment by senthil10** [comment]
Hej @talavis, Can kindly check if it is ok now, Tack!

**Review by talavis — CHANGES_REQUESTED** [review]
The local code seems fine, but something seems iffy with the imported scripts. Nothing is generated in the `output` folder.

```
root@e5ea11eb37b4:/code# python "$VACCINE_SCRIPTS_PATH"/vaccine_indicator_barchart.py --output-dir $CODE_PATH/output
/code/covid-portal-visualisations/Vaccine_page/vaccine_livetext.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dose_data["Vacc_perc_population"] = (dose_data["Antal vaccinerade"]/Swedish_population) * 100
root@e5ea11eb37b4:/code# ls output/
root@e5ea11eb37b4:/code#
```

(my "request changes" is related to that; I don't want anything non-functional merged). Did it work for you when you tested it?

**Comment by senthil10** [comment]
Yes, it worked all the way through (including uploading to blob server) for me when I tested locally. That warning message is numpy related, but that shouldn't affect the output generation.

**Comment by talavis** [comment]
> Yes, it worked all the way through (including uploading to blob server) for me when I tested locally. That warning message is numpy related, but that shouldn't affect the output generation.

Did you test it inside the container? That's where it matters.

**Comment by senthil10** [comment]
```
python "$VACCINE_SCRIPTS_PATH"/vaccine_indicator_barchart.py --output-dir $CODE_PATH/output
```
I think you ran this in console directly? is the `$CODE_PATH` set in the env while running? If not I think the file will be saved in `/output` rather than `./output` ?

**Comment by talavis** [comment]
> ```
> python "$VACCINE_SCRIPTS_PATH"/vaccine_indicator_barchart.py --output-dir $CODE_PATH/output
> ```
> 
> I think you ran this in console directly? is the `$CODE_PATH` set in the env while running? If not I think the file will be saved in `/output` rather than `./output` ?

The environment was set up correctly.

Direct run of the whole script:
```
root@4fb279626fef:/code# ./runner_weekly.sh
/.../ (the warnings from pandas etc)
root@4fb279626fef:/code# cd output/
root@4fb279626fef:/code/output# ls
covid-portal-abstracts_all.png 
covid-portal-abstracts_h2020.png
covid-portal-abstracts_kaw.png
covid-portal-abstracts_vr.png
covid-portal-titles_all.png
covid-portal-titles_h2020.png
covid-portal-titles_kaw.png
covid-portal-titles_vr.png
root@4fb279626fef:/code/output#

**Review by talavis — APPROVED** [review]

**Pull request merged**
