### PR TITLE
FREYA-886 :: dc-dynamic cleanup

### PR DESCRIPTION
**Pull request by Ziip-dev**
Removes unused scripts.

Some data have become historic, hence there is no need to run their corresponding visualisation generator scripts on a regular basis anymore.

Also only keep main dependencies and update their versions.

### CODE REVIEW

**Comment by Ziip-dev** [comment]
- [x] update requirements
- [x] cleanup unused script

**Comment by Ziip-dev** [comment]
Good to go :)

**Comment by Ziip-dev** [comment]
- [x] update requirements
- [x] cleanup unused script

**Review by senthil10 — APPROVED** [review]
Looks good, will merge it. But release has to be done after the `pathogens-portal-visualisation` and `pathogens-portal-scripts` repo PRs are merged.

**Pull request merged**
